export const NFTs = [
    {
        key: 1,
        nftName: "FantomWorld Land 01",
        nftImage: [
            "/Assets/homes-nfts/firstLand.jpg",
            "/Assets/homes-nfts/secondLand.jpg",
            "/Assets/homes-nfts/thirdLand.jpg",
            "/Assets/homes-nfts/sixthLand.jpg",
        ],
        nftPrice: "0.15",
        amount: "1 of 32",
    },
    {
        key: 2,
        nftName: "FantomWorld Land 02",
        nftImage: [
            "/Assets/homes-nfts/secondLand.jpg",
            "/Assets/homes-nfts/fourthLand.jpg",
            "/Assets/homes-nfts/fifthLand.jpg",
            "/Assets/homes-nfts/sixthLand.jpg",
        ],
        nftPrice: "0.15",
        amount: "1 of 32",
    },
    {
        key: 3,
        nftName: "FantomWorld Land 03",
        nftImage: [
            "/Assets/homes-nfts/thirdLand.jpg",
            "/Assets/homes-nfts/fourthLand.jpg",
            "/Assets/homes-nfts/seventhLand.jpg",
            "/Assets/homes-nfts/eighthLand.jpg",
        ],
        nftPrice: "0.15",
        amount: "1 of 32",
    },
    {
        key: 4,
        nftName: "FantomWorld Land 04",
        nftImage: [
            "/Assets/homes-nfts/fourthLand.jpg",
            "/Assets/homes-nfts/fifthLand.jpg",
            "/Assets/homes-nfts/seventhLand.jpg",
            "/Assets/homes-nfts/eighthLand.jpg",
        ],
        nftPrice: "0.15",
        amount: "1 of 32",
    },
    {
        key: 5,
        nftName: "FantomWorld Land 05",
        nftImage: [
            "/Assets/homes-nfts/fifthLand.jpg",
            "/Assets/homes-nfts/seventhLand.jpg",
            "/Assets/homes-nfts/eighthLand.jpg",
            "/Assets/homes-nfts/firstLand.jpg",
        ],
        nftPrice: "0.15",
        amount: "1 of 32",
    },
    {
        key: 6,
        nftName: "FantomWorld Land 06",
        nftImage: [
            "/Assets/homes-nfts/sixthLand.jpg",
            "/Assets/homes-nfts/fifthLand.jpg",
            "/Assets/homes-nfts/fourthLand.jpg",
            "/Assets/homes-nfts/eighthLand.jpg",
        ],
        nftPrice: "0.15",
        amount: "1 of 32",
    },
    {
        key: 7,
        nftName: "FantomWorld Land 07",
        nftImage: [
            "/Assets/homes-nfts/seventhLand.jpg",
            "/Assets/homes-nfts/eighthLand.jpg",
            "/Assets/homes-nfts/firstLand.jpg",
            "/Assets/homes-nfts/secondLand.jpg",
        ],
        nftPrice: "0.15",
        amount: "1 of 32",
    },
    {
        key: 8,
        nftName: "FantomWorld Land 08",
        nftImage: [
            "/Assets/homes-nfts/eighthLand.jpg",
            "/Assets/homes-nfts/fifthLand.jpg",
            "/Assets/homes-nfts/secondLand.jpg",
            "/Assets/homes-nfts/thirdLand.jpg",
        ],
        nftPrice: "0.15",
        amount: "1 of 32",
    },
]
